# Generated by Django 4.1.3 on 2023-01-13 11:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forgot_password', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileMODEL',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionMODEL',
        ),
    ]
