# Generated by Django 4.1.3 on 2023-01-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0011_phonemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneModel',
            new_name='Phone_MODELl',
        ),
    ]
