# Generated by Django 4.1.3 on 2023-01-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0013_rename_otp_model_otpmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneMODELl',
        ),
    ]
