# Generated by Django 4.1.3 on 2022-12-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0006_rename_otp_otp_model_alter_otp_model_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_model',
            name='otp_otp',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
