# Generated by Django 4.1.3 on 2022-12-25 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0007_alter_otp_model_otp_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp_model',
            old_name='otp_otp',
            new_name='otp_one_time_password',
        ),
    ]
