# Generated by Django 4.1.3 on 2022-12-25 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0008_rename_otp_otp_otp_model_otp_one_time_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp_model',
            old_name='otp_one_time_password',
            new_name='otp_otp',
        ),
    ]
