# Generated by Django 4.1.3 on 2023-02-16 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(db_index=True, max_length=200)),
                ('pro_slug', models.SlugField(max_length=200)),
                ('pro_image', models.ImageField(blank=True, upload_to='')),
                ('pro_description', models.TextField(blank=True)),
                ('pro_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pro_stock', models.PositiveIntegerField()),
                ('pro_available', models.BooleanField(default=True)),
                ('pro_created', models.DateTimeField(auto_now_add=True)),
                ('pro_updated', models.DateTimeField(auto_now=True)),
                ('pro_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='category.categorymodel')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-pro_created',),
                'index_together': {('id', 'pro_slug')},
            },
        ),
    ]
