# Generated by Django 4.1.3 on 2023-02-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_product_productmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductMODEL',
        ),
    ]
