# Generated by Django 4.1.3 on 2023-02-22 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0019_alter_categorymodel_options_and_more'),
        ('product', '0003_delete_productmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=200)),
                ('product_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('product_image', models.ImageField(db_index=True, default='Default_Image.png', upload_to='Productes_File_Photo/', verbose_name='Image Preview')),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_stock_quantity_positive_integer', models.PositiveIntegerField()),
                ('product_stock_quantity', models.IntegerField()),
                ('product_available', models.BooleanField(default=True)),
                ('product_created', models.DateTimeField(auto_now_add=True)),
                ('product_updated', models.DateTimeField(auto_now=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.categorymodel', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-product_created',),
                'index_together': {('id', 'product_slug')},
            },
        ),
    ]
