# Generated by Django 4.1.3 on 2023-02-22 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productmodel_product_stock_quantity_positive_integer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductImage_image', models.ImageField(db_index=True, default='Default_Image.png', upload_to='Productes_File_Photo/', verbose_name='Image Preview')),
                ('ProductImage_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='product.productmodel')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Products Images',
                'ordering': ('-ProductImage_product',),
                'index_together': {('id',)},
            },
        ),
    ]
