# Generated by Django 4.1.3 on 2023-02-22 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productimagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagemodel',
            name='ProductImage_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='product.productmodel', verbose_name='Product Name'),
        ),
    ]
