# Generated by Django 4.1.3 on 2023-02-25 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0021_initial'),
        ('product', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.subcategorybranchmodel', verbose_name='Product'),
        ),
    ]
