# Generated by Django 4.1.3 on 2023-02-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='cat_category_image',
            field=models.ImageField(default=1, upload_to='catgories'),
            preserve_default=False,
        ),
    ]
