# Generated by Django 4.1.3 on 2023-02-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_delete_productmodel'),
        ('category', '0002_categorymodel_cat_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryMODEL',
        ),
    ]
