# Generated by Django 4.1.3 on 2023-02-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_alter_categoryimagemodel_caim_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='CATE_category_image',
            field=models.ImageField(blank=True, db_index=True, upload_to='catgories', verbose_name='Image'),
        ),
        migrations.DeleteModel(
            name='CategoryImageMODEL',
        ),
    ]
