# Generated by Django 4.1.3 on 2023-02-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_categorymodel_cate_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='CATE_category_image',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='catgoryFile_Photo', verbose_name='Image Preview'),
        ),
    ]
