# Generated by Django 4.1.3 on 2023-02-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_alter_categorymodel_cate_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='CATE_category_image',
            field=models.ImageField(db_index=True, default='Default_Image.png', upload_to='Catgory_File_Photo/', verbose_name='Image Preview'),
        ),
    ]
