# Generated by Django 4.1.3 on 2023-02-17 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_delete_categorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(db_index=True, max_length=200)),
                ('c_slug', models.SlugField(max_length=200, unique=True)),
                ('c_category_image', models.ImageField(upload_to='catgories')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
                'ordering': ('c_name',),
            },
        ),
        migrations.CreateModel(
            name='CategorySubMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_name', models.CharField(db_index=True, max_length=200)),
                ('cs_slug', models.SlugField(max_length=200, unique=True)),
                ('cs_category_image', models.ImageField(upload_to='categories_sub')),
                ('cs_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_sub', to='category.categorymodel')),
            ],
        ),
    ]
