# Generated by Django 4.1.3 on 2023-02-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorysubmodel',
            name='cs_category',
        ),
        migrations.DeleteModel(
            name='CategoryMODEL',
        ),
        migrations.DeleteModel(
            name='CategorySubMODEL',
        ),
    ]
