# Generated by Django 4.1.3 on 2023-02-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorysubmodel',
            name='CSUB_category',
        ),
        migrations.DeleteModel(
            name='CategoryMODEL',
        ),
        migrations.DeleteModel(
            name='CategorySubMODEL',
        ),
    ]
