# Generated by Django 4.1.3 on 2023-02-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0008_remove_categorysubmodel_csub_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATE_name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('CATE_slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('CATE_available', models.BooleanField(db_index=True, default=True, verbose_name='Available')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('CATE_name',),
            },
        ),
        migrations.CreateModel(
            name='CategorySubMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CSUB_name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('CSUB_slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('CSUB_category_image', models.ImageField(blank=True, db_index=True, upload_to='catgories_sub', verbose_name='Image')),
                ('CSUB_available', models.BooleanField(db_index=True, default=True, verbose_name='Available')),
                ('CSUB_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_sub', to='category.categorymodel', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
                'ordering': ('CSUB_name',),
            },
        ),
        migrations.CreateModel(
            name='CategoryImageMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAIM_category_image', models.ImageField(blank=True, db_index=True, upload_to='catgories', verbose_name='Image')),
                ('CAIM_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='category.categorymodel', verbose_name='Category Name')),
            ],
            options={
                'verbose_name_plural': 'Categories Images',
                'ordering': ('CAIM_category',),
            },
        ),
    ]
