# Generated by Django 4.1.3 on 2023-02-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0015_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'ordering': ('Cate_name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='categorymodel',
            old_name='CATE_available',
            new_name='Cate_available',
        ),
        migrations.RenameField(
            model_name='categorymodel',
            old_name='CATE_category_image',
            new_name='Cate_category_image',
        ),
        migrations.RenameField(
            model_name='categorymodel',
            old_name='CATE_name',
            new_name='Cate_name',
        ),
        migrations.RenameField(
            model_name='categorymodel',
            old_name='CATE_slug',
            new_name='Cate_slug',
        ),
    ]
