# Generated by Django 4.1.3 on 2023-02-19 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0016_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCat_name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('SubCat_slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('SubCat_category_image', models.ImageField(db_index=True, default='Default_Image.png', upload_to='Catgories_Sub_File_Photo/', verbose_name='Image Preview')),
                ('SubCat_available', models.BooleanField(db_index=True, default=True, verbose_name='Available')),
                ('SubCat_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_sub', to='category.categorymodel', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
                'ordering': ('SubCat_name',),
            },
        ),
    ]
