# Generated by Django 4.1.3 on 2023-02-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productmodel_index_together_and_more'),
        ('category', '0019_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategorymodel',
            name='SubCat_category',
        ),
        migrations.DeleteModel(
            name='CategoryMODEL',
        ),
        migrations.DeleteModel(
            name='SubCategoryMODEL',
        ),
    ]
