# Generated by Django 4.1.3 on 2023-01-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersTable',
        ),
    ]
