# Generated by Django 4.1.3 on 2023-01-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_change', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UsersTable',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
