# Generated by Django 4.1.3 on 2023-01-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgot_password', '0002_rename_profile_profilemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionmodel',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userquestionmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProfileMODEL',
        ),
        migrations.DeleteModel(
            name='QuestionMODEL',
        ),
        migrations.DeleteModel(
            name='UserQuestionModel',
        ),
    ]
