# Generated by Django 4.1.3 on 2023-01-06 16:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whatsapp', '0002_alter_profilemodel_p_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendOtpToWhatsappMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SOTW_mobile', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('SOTW_created_at', models.DateTimeField(auto_now_add=True)),
                ('SOTW_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='P_User',
        ),
        migrations.DeleteModel(
            name='MobileMODEL',
        ),
        migrations.DeleteModel(
            name='ProfileMODEL',
        ),
    ]
