# Generated by Django 4.1.3 on 2023-01-06 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_sendotptowhatsappmodel_remove_profilemodel_p_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendotptowhatsappmodel',
            old_name='SOTW_mobile',
            new_name='SOTW_mobile_number',
        ),
    ]
