# Generated by Django 4.1.3 on 2023-01-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_rename_sotw_mobile_sendotptowhatsappmodel_sotw_mobile_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendotptowhatsappmodel',
            options={'ordering': ['SOTW_created_at']},
        ),
        migrations.AddField(
            model_name='sendotptowhatsappmodel',
            name='Is_whatsApp_active',
            field=models.BooleanField(default=False, help_text='Choose to activate WhatsApp service'),
        ),
    ]
