# Generated by Django 4.1.3 on 2023-01-07 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_alter_sendotptowhatsappmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendotptowhatsappmodel',
            name='SOTW_mobile_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='[\\+\\d]?(\\d{2,3}[-\\.\\s]??\\d{2,3}[-\\.\\s]??\\d{4}|\\(\\d{3}\\)\\s*\\d{3}[-\\.\\s]??\\d{4}|\\d{3}[-\\.\\s]??\\d{4})')]),
        ),
    ]
