# Generated by Django 4.1.3 on 2023-01-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_alter_sendotptowhatsappmodel_sotw_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_or_no', models.BooleanField(choices=[(True, 'Yes-نعم'), (False, 'No-لا')])),
            ],
        ),
        migrations.AlterField(
            model_name='sendotptowhatsappmodel',
            name='Is_whatsApp_active',
            field=models.BooleanField(choices=[(True, 'Yes-نعم'), (False, 'No-لا')], default=False, help_text='Choose to activate WhatsApp service'),
        ),
    ]
