# Generated by Django 4.1.3 on 2023-01-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0008_alter_sendotptowhatsappmodel_is_whatsapp_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendotptowhatsappmodel',
            name='Is_whatsApp_active',
            field=models.BooleanField(blank=True, default=False, help_text='Choose to activate WhatsApp service', null=True),
        ),
    ]
