# Generated by Django 4.1.3 on 2023-01-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0010_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendotptowhatsappmodel',
            name='Is_whatsApp_active',
            field=models.BooleanField(default=False, help_text='Choose to activate WhatsApp service'),
        ),
    ]
