# Generated by Django 4.1.3 on 2023-01-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0013_remove_sendotptowhatsappmodel_sotw_is_whatsapp_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendotptowhatsappmodel',
            name='Is_whatsApp_active',
        ),
        migrations.AddField(
            model_name='sendotptowhatsappmodel',
            name='SOTW_Is_whatsApp_active',
            field=models.BooleanField(default=False, help_text='Choose to activate WhatsApp service'),
        ),
    ]
