# Generated by Django 4.1.3 on 2023-01-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0014_remove_sendotptowhatsappmodel_is_whatsapp_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendotptowhatsappmodel',
            old_name='SOTW_Is_whatsApp_active',
            new_name='Is_whatsApp_active',
        ),
    ]
