# Generated by Django 4.1.3 on 2023-01-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0015_rename_sotw_is_whatsapp_active_sendotptowhatsappmodel_is_whatsapp_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendotptowhatsappmodel',
            old_name='Is_whatsApp_active',
            new_name='SOTW_Is_whatsApp_active',
        ),
    ]
