# Generated by Django 4.1.3 on 2023-02-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0016_rename_is_whatsapp_active_sendotptowhatsappmodel_sotw_is_whatsapp_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendotptowhatsappmodel',
            options={'ordering': ['SOTW_created_at'], 'verbose_name_plural': 'Send OTP'},
        ),
    ]
